<?php
declare(strict_types=1);

return [
    'iblock_id' => 122,
    'call_id_property_code' => 'CALL_ID',
    'call_datetime_property_code' => 'CALL_DATETIME',
    'is_booked_property_code' => 'IS_BOOKED',
    'fill_call_datetime_from_received_at' => true,
    'call_datetime_prefer_received_at' => true,
    'call_datetime_timezone' => 'Europe/Moscow',
    'service_timezone' => 'Europe/Moscow',
    'family_offer_status_property_code' => 'FAMILY_OFFER_STATUS',
    'default_base_score' => 27,
    'write_logs' => true,
    'log_path' => 'storage/integration.log',
    'max_log_bytes' => 2097152,
    'fail_fast_on_bitrix_error' => false,
    'upsert_by_call_id' => false,
    'bitrix_prolog_before_path' => null,
    'criteria_property_map' => [
        1 => 'DED_CALL_GOAL',
        2 => 'DED_CLINIC_NAME',
        3 => 'DED_EMPLOYEE_INTRO',
        4 => 'DED_PROGRAMMING',
        5 => 'DED_NEEDS',
        6 => 'DED_OFFER_PACKAGING',
        7 => 'DED_BOOKING',
        8 => 'DED_CONTRAINDICATIONS',
        9 => 'DED_PRICE_ANSWER',
        10 => 'DED_CONFIDENCE',
        11 => 'DED_NEXT_ACTION',
        12 => 'DED_CLIENT_QUESTIONS',
        13 => 'DED_APPOINTMENT_DURATION',
        14 => 'DED_COMPETENCE',
        15 => 'DED_FAREWELL',
        16 => 'DED_OBJECTIONS',
        17 => 'DED_FAMILY_OFFER',
    ],
    'aggregate_property_map' => [
        'BASE_SCORE' => 'BASE_SCORE',
        'FINAL_SCORE' => 'FINAL_SCORE',
        'DEDUCTION_TOTAL' => 'DEDUCTION_TOTAL',
        'CRITERIA_TOTAL' => 'CRITERIA_TOTAL',
        'FINAL_SCORE_PERCENT' => 'FINAL_SCORE_PERCENT',
    ],
    'extra_property_map' => [
        'PHONE_NUMBER' => 'PHONE_NUMBER',
        'PORTAL_NUMBER' => 'PORTAL_NUMBER',
        'CRM_ENTITY_TYPE' => 'CRM_ENTITY_TYPE',
        'CRM_ENTITY_ID' => 'CRM_ENTITY_ID',
        'CRM_ACTIVITY_ID' => 'CRM_ACTIVITY_ID',
        'CALL_START_DATE' => 'CALL_START_DATE',
        'PORTAL_USER_ID' => 'PORTAL_USER_ID',
        'CALL_DURATION' => 'CALL_DURATION',
        'CALL_TYPE' => 'CALL_TYPE',
    ],
];
